name: update_submodules

on:
  workflow_dispatch:

jobs:
  update_submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: main
          submodules: recursive
          token: ${{ secrets.MS3_BOT_TOKEN }}
      - name: Configure git
        working-directory: ./main
        continue-on-error: true
        run: |
          git config --global user.name "ms3-bot"
          git config --global user.email dcml.annotators@epfl.ch
          git config --global user.token ${{ secrets.MS3_BOT_TOKEN }}
      - name: Pull latest updates into submodules
        working-directory: ./main
        run: |
          git submodule foreach "git checkout -f main | git clean -xfd | git reset --hard | git submodule foreach --recursive git clean -xfd | git submodule deinit -f . | git submodule update --init --recursive"
      - name: Gather metadata from submodules
        working-directory: ./main
        run: |
          python -m pip install ms3
          ms3 transform -D
      - name: Push files
        working-directory: ./main
        continue-on-error: true
        run: |
          git add -A
          git commit -m "Updated metadata from submodules"
          git push
